FROM continuumio/miniconda3:4.10.3

RUN apt-get update \
    && apt-get install -y build-essential procps

COPY environment_bcl2fastq.yml .

RUN conda env create -f environment_bcl2fastq.yml

RUN chmod 755 /root
RUN echo "conda activate bcl2fastq" >> ~/.bashrc
