name: Daedalus
channels:
  - bioconda/label/cf201901
  - conda-forge/label/cf201901
  - anaconda
  - guillaumecharbonnier
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - blas=1.0
  - boltons=19.2.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - contextlib2=0.6.0.post1
  - debtcollector=1.21.0
  - decorator=4.4.1
  - dit=1.2.3
  - httplib2=0.12.0
  - libgcc-ng=9.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - mkl=2017.0.3
  - muscle=3.8.1551
  - networkx=2.4
  - numpy=1.13.3
  - openssl=1.0.2u
  - pandas=0.25.3
  - pbr=5.4.2
  - pip=19.3.1
  - prettytable=0.7.2
  - python=3.6.2
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=6.2
  - requests=2.12.5
  - scipy=0.19.1
  - setuptools=36.4.0
  - six=1.13.0
  - sqlalchemy=1.3.15
  - sqlite=3.13.0
  - tk=8.5.18
  - wheel=0.29.0
  - wrapt=1.10.11
  - xz=5.2.3
  - zlib=1.2.11
  - pip:
    - argparse==1.4.0
    - bio==0.1.0
    - boto==2.49.0
    - boto3==1.12.19
    - botocore==1.15.19
    - click==7.1.1
    - docutils==0.15.2
    - jmespath==0.9.5
    - joblib==0.14.1
    - s3transfer==0.3.3
    - sample-sheet==0.1.0
    - scikit-learn==0.22.1
    - seqnetwork==0.1.0
    - smart-open==1.9.0
    - tabulate==0.8.6
    - terminaltables==3.1.0
    - urllib3==1.25.8

