name: VDJdetect
channels:
- anaconda
- bioconda
- defaults
dependencies:
- pip=19.2.3=py36_0
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
    - git+http://ghe-rss.roche.com/pls-red-packages/bam-streamer.git@v0.1.0
    - git+http://ghe-rss.roche.com/pls-red-packages/fastq-streamer.git@v0.1.0
    - git+http://ghe-rss.roche.com/pls-red-packages/VDJ-recombinant-detection.git@860a812
